import localFont from "next/font/local";
import "./globals.css";
import Provider from "./util/Provider";
import Siderbar from "@/components/Siderbar";
import Navrbar from "@/components/Navrbar";
import MenuBar from "@/components/MenuBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Learing Nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          {/* <Navrbar /> */}
          <MenuBar />
          <div className="flex">
          <Siderbar />
          <main>
            {children}
          </main>
          </div>
        </Provider>
      </body>
    </html>
  );
}
